version: '3.8'

services:
  frontend:
    image: node:18
    volumes:
      - ./:/app
    ports:
      - "5173:8080"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run build"
    networks:
      - my-network

networks:
  my-network:
    external: true