name: Deploy Frontend

on:
  push:
    branches:
      - master  # Укажите ветку, которую хотите использовать для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка SSH
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # Шаг 3: Копирование исходного кода на сервер
      - name: Copy source code to server
        run: |
          scp -r . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}

      # Шаг 4: Перезапуск Docker-контейнеров
      - name: Restart Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            cd ${{ secrets.REMOTE_PATH }}
            docker-compose down
            docker-compose build
            docker-compose up -d
          "
